/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;

export interface BumpkinShop extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): BumpkinShop;
  clone(): BumpkinShop;
  methods: {
    addGameRole(_game: string): NonPayableTransactionObject<void>;

    addItemBatch(
      items: {
        tokenId: number | string | BN;
        maxSupply: number | string | BN;
        releaseDate: number | string | BN;
      }[]
    ): NonPayableTransactionObject<void>;

    feeWallet(): NonPayableTransactionObject<string>;

    gameAddGameRole(_game: string): NonPayableTransactionObject<void>;

    gameRemoveGameRole(_game: string): NonPayableTransactionObject<void>;

    gameRoles(arg0: string): NonPayableTransactionObject<boolean>;

    getItemBatch(
      tokenIds: (number | string | BN)[]
    ): NonPayableTransactionObject<
      { tokenId: string; maxSupply: string; releaseDate: string }[]
    >;

    mint(
      tokenId: number | string | BN,
      deadline: number | string | BN,
      price: number | string | BN,
      supply: number | string | BN,
      fee: number | string | BN,
      signature: string | number[]
    ): PayableTransactionObject<void>;

    owner(): NonPayableTransactionObject<string>;

    removeGameRole(_game: string): NonPayableTransactionObject<void>;

    removeItemBatch(
      tokenIds: (number | string | BN)[]
    ): NonPayableTransactionObject<void>;

    renounceOwnership(): NonPayableTransactionObject<void>;

    signer(): NonPayableTransactionObject<string>;

    transferFeeWallet(_feeWallet: string): NonPayableTransactionObject<void>;

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;

    transferSigner(_signer: string): NonPayableTransactionObject<void>;
  };
  events: {
    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;
}
