const NETWORK = import.meta.env.VITE_NETWORK as "mainnet" | "mumbai";
const API_URL = import.meta.env.VITE_API_URL;
const TOKEN_CONTRACT = import.meta.env.VITE_TOKEN_CONTRACT;
const SUNFLOWER_LAND_CONTRACT = import.meta.env.VITE_SUNFLOWER_LAND_CONTRACT;
const BUMPKIN_DETAILS_CONTRACT = import.meta.env.VITE_BUMPKIN_DETAILS_CONTRACT;
const BUMPKIN_MINTER_CONTRACT = import.meta.env.VITE_BUMPKIN_MINTER_CONTRACT;
const BUMPKIN_ITEMS_CONTRACT = import.meta.env.VITE_BUMPKIN_ITEMS_CONTRACT;
const BUMPKIN_SHOP_CONTRACT = import.meta.env.VITE_BUMPKIN_SHOP_CONTRACT;
const BUMPKIN_EQUIPPER_CONTRACT = import.meta.env
  .VITE_BUMPKIN_EQUIPPER_CONTRACT;
const BUMPKIN_CONTRACT = import.meta.env.VITE_BUMPKIN_CONTRACT;
const ALCHEMY_RPC = import.meta.env.VITE_ALCHEMY_RPC as string;

const POLYGON_CHAIN_ID = NETWORK === "mainnet" ? 137 : 80001;

export const CONFIG = {
  NETWORK,
  POLYGON_CHAIN_ID,
  API_URL,
  TOKEN_CONTRACT,
  BUMPKIN_CONTRACT,
  BUMPKIN_DETAILS_CONTRACT,
  BUMPKIN_MINTER_CONTRACT,
  BUMPKIN_ITEMS_CONTRACT,
  BUMPKIN_EQUIPPER_CONTRACT,
  BUMPKIN_SHOP_CONTRACT,
  SUNFLOWER_LAND_CONTRACT,
  ALCHEMY_RPC,
};
