export const ERRORS = {
  NO_WEB3: "NO_WEB3",
  WRONG_CHAIN: "WRONG_CHAIN",
  PHANTOM_WALLET_NOT_SUPPORTED: "PHANTOM_WALLET_NOT_SUPPORTED",
  NO_FARM: "NO_FARM",
  FAILED_REQUEST: "FAILED_REQUEST",
  REJECTED_TRANSACTION: "REJECTED_TRANSACTION",
  BLOCKED: "BLOCKED",
  NETWORK_CONGESTED: "NETWORK_CONGESTED",
  UNPREDICTABLE_GAS_LIMIT: "UNPREDICTABLE_GAS_LIMIT",

  // Blockchain session has changed - they are doing something sneaky refreshing the browser
  SESSION_EXPIRED: "SESSION_EXPIRED",

  // Server errors
  DISCORD_USER_EXISTS: "DISCORD_USER_EXISTS",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  MAINTENANCE: "MAINTENANCE",

  // Wishing well errors
  NO_TOKENS: "NO_TOKENS",

  // Equip listed item error
  CANNOT_EQUIP_LISTED: "CANNOT_EQUIP_LISTED",
  // Sequence
  SEQUENCE_NOT_CONNECTED: "SEQUENCE_NOT_CONNECTED",
};

export type ErrorCode = keyof typeof ERRORS;
